version: '3.8'

services:
  x-posts-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: x-posts-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DEBUG=puppeteer:*
